src/generator/__tests__/generator-basic-test.js, src/generator/index.js
I've fixed this way (in generator) to allow omitting `node.expressions = []` while traversing.
=> Fix empty character classes

index.js, src/generator/index.js, src/parser/index.js, src/traverse/index.js
Also prevents `quantifier` from leaking to global.
=> Add strict mode

__tests__/integration-test.js, index.js
Closes #12.
I would argue than instead of adding another method, `parse` should do `ToString`.
- It is simpler for users of API, makes first contact with module more pleasant ("Unexpected end of input" error is not very helpful).
- Less bloat.
- Will make `traverse` API simpler (`traverseFromRegExp` does not look right).
- Very JavaScripty and feels natural.
=> Coerce to string in `parse`

src/traverse/__tests__/node-path-test.js
fixes some errors with trailing commas in function parameters when not having ES2017
see [Trailing commas - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)
=> remove some commas that generated errors

src/traverse/README.md, src/traverse/__tests__/node-path-test.js, src/traverse/node-path.js
we need this
* to navigate to parent without knowing implementation details (NodePath, node.parent etc.)
* to have a consistent API
=> add getParent() to NodePath

src/optimizer/transforms/__tests__/group-single-chars-to-char-class-test.js, src/optimizer/transforms/group-single-chars-to-char-class.js
Sorry, just forgot about that simple case: `/a|b|c/` -> `/[abc]/`.
Also here is another feature - group merge: `/[12]|3|4/` -> `/[1234]/`
And also chars are now sorted, so `/[43]|a|b|[53]|c|[9]/` will be optimized to `/[3459abc]/`
=> better disjunction processor

index.d.ts
When published to npm, this will help TS developers to automatically get strong typings when importing a module.
Covering only parser for now as that's the most interesting for me, but I'm sure someone else can pick it up and add other APIs.
Semi-related to #34.
=> Add initial TypeScript definitions

README.md, __tests__/integration-test.js, src/parser/README.md, src/parser/__tests__/parser-basic-test.js, src/parser/__tests__/parser-extended-test.js, src/parser/generated/regexp-tree.js, src/parser/regexp.bnf, src/transform/__tests__/transform-basic-test.js, src/traverse/__tests__/node-path-test.js, src/traverse/__tests__/traverse-basic-test.js
This is a fix for #92.
I added a `codePoint` key on `Char` tokens, so that we can compare all syntaxes the same way.
I had to handle a special case for `control` chars, which seem to not be allowed in character ranges.
I also handled `meta` character classes short forms (`\w`, `\s`, etc.) using `codePoint` with the value `NaN`. I'm not really happy with this. In fact, something like `[a-\s]` should not even be parsed as a character class in the first place, but rather as three separate chars.
=> Handle codePoints in checkClassRange()

src/optimizer/transforms/__tests__/disjunction-remove-duplicates-transform-test.js, src/optimizer/transforms/disjunction-remove-duplicates-transform.js, src/optimizer/transforms/index.js
Hi! This is an attempt to fix #94.
The issue I'm facing is that it only replaces one duplicate at a time.
Thus calling `regexp-tree -e "/(ab|ab|ab|ab)/" -o` returns `/(ab|ab|ab)/`, which is kind of annoying.
Any idea to make it more useful?
=> Remove duplicates in disjunctions Fix #94

src/optimizer/transforms/__tests__/quantifier-range-to-symbol-transform-test.js, src/optimizer/transforms/quantifier-range-to-symbol-transform.js
This adds support for `/a{0,}/` -> `/a*/` in Optimizer.
=> Add support for {0,} -> * in optimizer's quantifier-range-to-symbol transform

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/transforms/__tests__/char-escape-unescape-transform-test.js, src/optimizer/transforms/char-escape-unescape-transform.js
We don't want `/[\^a]/` to be optimized to `/[^a]/`.
=> Optimizer: don't unescape \^ in character class

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/index.js
Currently, optimizing `/a|a/` gives `/[a]/` and optimizing again `/[a]/` gives `/a/`.
We should get the most optimized result directly.
This PR lets the optimizer run until it finds the best optimization. The drawback is that it has to run minimum twice to know...
=> Optimizer should run until it finds the best optimization

src/optimizer/transforms/__tests__/ungroup-transform-test.js, src/optimizer/transforms/index.js, src/optimizer/transforms/ungroup-transform.js
This transform removes unnecessary groups:
`/a(?:bc)d/` -> `/abcd/`
`/(?:ab|bc)/` -> `/ab|bc/`
`/(?:a)+/` -> `/a+/`
It does not remove capturing groups, nor disjunctions other than top-level ones, nor complex groups with quantifier:
`/a(bc)d/`, `/a(?:ab|bc)d/`, `/(?:ab)+/` are left unchanged.
=> Optimizer: remove unnecessary groups

src/optimizer/transforms/__tests__/disjunction-remove-duplicates-transform-test.js, src/optimizer/transforms/__tests__/group-single-chars-to-char-class-test.js, src/optimizer/transforms/__tests__/ungroup-transform-test.js, src/optimizer/transforms/disjunction-remove-duplicates-transform.js, src/optimizer/transforms/group-single-chars-to-char-class.js, src/optimizer/transforms/ungroup-transform.js
This PR prevents the optimizer from throwing errors when handling empty groups or empty parts:
Optimizing `/a(?:)b/` used to throw in the `ungroup` transform. Now it leaves the regexp as it is.
Optimizing `/a||/` used to throw in the `disjunction-remove-duplicates` transform. Now it handles it properly and optimizes as `/a|/`.
Optimizing `/a|b|/` used to throw in the `group-single-chars-to-char-class` transform. Now it leaves the regexp as it is.
In the last case, I wonder if `[ab]?` would be an appropriate optimization. What is your opinion on this @DmitrySoshnikov ?
Also, I intend to add a specific transform to handle empty (non-capturing) groups at some point.
=> Optimizer: don't throw errors on empty groups

src/optimizer/transforms/__tests__/remove-empty-group-transform-test.js, src/optimizer/transforms/index.js, src/optimizer/transforms/remove-empty-group-transform.js
This PR provides a transform to remove empty groups in optimizer:
`/a(?:)b/` -> `/ab/`
`/a|(?:)|b/` -> `/a||b/`
It does not remove top-level empty group if alone (a.k.a the "empty regexp"):
`/(?:)/` is left unchanged.
`/(?:)+/` -> `/(?:)/`
=> Optimizer: remove non-capturing empty groups

src/traverse/index.js
This is just to be consistent with per-node handlers.
=> Traverse: allow explicit stop of the traversal when using catch-all handler

src/traverse/node-path.js
This fixes a weird bug I had with nodes existing in Registry being `null`.
=> Traverse: Delete node from NodePath registry when removed

src/optimizer/transforms/__tests__/combine-repeating-patterns-transform-test.js, src/optimizer/transforms/combine-repeating-patterns-transform.js, src/optimizer/transforms/index.js, src/traverse/node-path.js
This transform combines repeating patterns in alternatives. It is divided in three parts:
Look for two repeating patterns and combine them in a Repetition:
`/abcabc/` -> `/(?:abc){2}/`
Look for a pattern existing in a Repetition on the left:
`/(?:abc){2}abc/` -> `/(?:abc){3}/`
Look for a pattern on the left that matches a Repetition:
`/abc(?:abc){2}/` -> `/(?:abc){3}/`
**Note that this PR depends on (and includes) PR #106.**
=> Combine repeating patterns transform

src/transform/__tests__/transform-utils-test.js, src/transform/utils.js
This PR prevents `disjunctionToList` from throwing an error when processing `/|/`.
=> Transform: Prevent disjunctionToList from throwing on /|/

src/optimizer/transforms/__tests__/char-escape-unescape-transform-test.js, src/optimizer/transforms/char-escape-unescape-transform.js
This PR handles to TODOs in the `char-escape-unescape` transform.
It unescapes `\^` in character class except when it's in first position and the char class is not negative:
`/[\^a]/` -> `/[\^a]/`
`/[a\^]/` -> `/[a^]/`
`/[^\^]/` -> `/[^^]/`
It unescapes `\-` in character class when it's in first or last position:
`/[a\-z]/` -> `/[a\-z]/`
`/[\-a]/` -> `/[-a]/`
`/[a\-]/` -> `/[a-]/`
It unescapes `\{` except when it does look like a range quantifier:
`/\{/` -> `/{/`
`/\{3}/` -> `/\{3}/`
`/\{3,}/` -> `/\{3,}/`
`/\{3,4}/` -> `/\{3,4}/`
It unescapes `\}` except when it does look like a range quantifier:
`/\}/` -> `/}/`
`/{3\}/` -> `/{3\}/`
`/{3,\}/` -> `/{3,\}/`
`/{3,4\}/` -> `/{3,4\}/`
=> Optimizer: Unescape ^ - { } when safe

src/optimizer/transforms/char-class-to-single-char-transform.js
The `char-class-to-single-char` transform must escape `$`, `.`, `/`, `{`, `}` and `|` when turning them into single chars.
`/[$]/`-> `/\$/`
Also, I wondered about the `$` char in thoses regexps: [L61](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-class-to-single-char-transform.js#L61) and [L65](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-class-to-single-char-transform.js#L65). What is it for?
=> Optimizer: Escape $ . / { } | in char-class-to-single-char transform

index.js, src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/index.js, src/optimizer/transforms/index.js
This PR adds a `whitelist` parameter to the `optimize` method, as suggested in #81.
This could be a first step towards a list of optional ("loose") transforms that can only be performed when explicitely added to the whitelist.
I based this exactly on the compat-transpiler behaviour.
Alternatively, since it might be tedious to list all optimization transforms, we might want to consider using an object instead, with transform names as keys and booleans as values.
=> Optimizer: Add whitelist parameter to optimize()

src/optimizer/transforms/char-class-to-single-char-transform.js
Following the discussion in #108, I'm pretty sure this `$` character is a typo. I can't think of any use case where we'd want to consider `$` as a meta character that can be inversed.
=> Optimizer: Remove $ from list of metas in char-class-to-single-car transform

src/optimizer/transforms/__tests__/char-class-to-meta-transform-test.js, src/optimizer/transforms/char-class-to-meta-transform.js, src/traverse/index.js
The meaning of `\w` is extended when regexp has `i` and `u` flags so we should not do the optimization in this case.
=> Optimizer: convert char class to \w differently depending on i and u flags

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/transforms/__tests__/char-class-classranges-merge-transform-test.js, src/optimizer/transforms/char-class-classranges-merge-transform.js, src/optimizer/transforms/index.js
The transform is this PR processes character classes to merge class ranges.
It merges chars in class ranges:
`/[a-fe]/` -> `/[a-f]/`
It merges class ranges one into another:
`/[a-zc-g]/` -> `/[a-z]/`
It expends class ranges to include chars:
`/[a-cd]` -> `[a-d]/`
`/[ab-d]` -> `[a-d]/`
It combines class ranges that overlap or are contiguous:
`/[a-fc-k]` -> `[a-k]/`
`/[a-cd-k]` -> `[a-k]/`
It merges chars and class ranges into meta classes:
`/[\wac-f$]/` -> `/[\w$]/`
`/[\w\u017f$/iu` -> `/[\w$]/iu`
It merges meta classes one into another:
`/[\w\d$]/` -> `/[\w$]/`
`/[\D\W\s9]/` -> `/[\D9]/`
=> Optimizer: Merge class ranges

src/optimizer/index.js
Optimizer used to throw an error when used with regexps containing new syntax (like named captures or the `x` flag), since #101 was merged.
It was because I made the Transformer generate an actual RegExp instead of using a string representation. This PR fixes it!
=> Optimizer: Don't throw on new syntax

src/optimizer/transforms/__tests__/combine-repeating-patterns-transform-test.js, src/optimizer/transforms/combine-repeating-patterns-transform.js, src/optimizer/transforms/quantifiers-merge-transform.js, src/transform/__tests__/transform-utils-test.js, src/transform/utils.js
I forgot a case in the `increaseQuantifierByOne` function in the `combine-repeating-patterns` transform leading to incorrect optimization of `/(?:abc)+abc/` into `/(?:abc)+/` instead of `/(?:abc){2,}/`.
This PR fixes the case and moves the function to the `utils.js` file since the same behaviour is used in the `quantifiers-merge` transform.
=> Optimizer: Fix (?:abc)+abc optimization in combine-repeating-patterns

src/optimizer/transforms/__tests__/char-class-classranges-merge-transform-test.js, src/optimizer/transforms/char-class-classranges-merge-transform.js
This PR updates the char-class-classranges-merge transform to handle sequences of chars:
`/[abcdef]/` -> `/[a-f]/`
For the sake of readability, I chose to only merge chars being in `\w` or being coded (either unicode, hex, octal or decimal). I'm not sure about this choice though.
Should the optimizer transform `/[<=>?]/` into `/[<-?]/`?
=> Optimizer: Combine chars sequences into class ranges in char-class-classranges-merge transform

src/optimizer/transforms/__tests__/char-surrogate-pair-to-single-unicode-transform-test.js, src/optimizer/transforms/char-surrogate-pair-to-single-unicode-transform.js, src/optimizer/transforms/index.js
`/\ud83d\ude80/u` -> `/\u{1f680}/u`
=> Optimizer: When u flag is set, convert surrogate pairs to single unicode code point

src/parser/generated/regexp-tree.js, src/parser/regexp.bnf
Because of the definition of `CHAR`, the parser currently throws on `/\\/u` and `/\|/u`. This PR fixes this.
=> Parser: Don't throw errors on escaped \ and | chars when u flag is set

.eslintrc.json, src/parser/generated/regexp-tree.js, src/parser/regexp.bnf
The [no-control-regex](https://eslint.org/docs/rules/no-control-regex) rule may be useful for most people, but in our case, there are situations where we might want to include all those chars.
(Also, the rule is quite over-restrictive since it doesn't allow chars like `\xA9`: `©`)
This PR includes #130.
=>  ESLint: Disable the no-control-regex rule

src/optimizer/transforms/__tests__/char-code-to-simple-char-transform-test.js, src/optimizer/transforms/char-code-to-simple-char-transform.js, src/optimizer/transforms/index.js
The transform in this PR converts coded chars (unicode, hex, oct, dec) to simple chars when they are in the range of ASCII printable chars.
`/\u0041\u0020\u007e/` -> `/A ~/`
It will do the same on class ranges but only when they're included in either `0-9`, `a-z` or `A-Z`.
`/[\x42-\x4c\x6d-\x72]/` -> `/[B-Lm-r]/`
But `/[\u{5a}-\u{61}]/u` is _not_ converted to `/[Z-a]/u`.
It will escape chars when needed (naively, without additional checks):
`/\u005b\u{28}[\u{5c}\x5e]/u` -> `/\[\([\\\^]/u`
This PR relies on (and includes) #130 and #131. Otherwise the tests won't run.
(I'm not sure how annoying it is on your side to handle "PRs with dependencies". If you know of a better way to do this, let me now.)
=> Optimizer: Transform coded chars to simple chars 

src/optimizer/transforms/__tests__/char-class-classranges-merge-transform-test.js, src/optimizer/transforms/char-class-classranges-merge-transform.js
This fixes #156.
EDIT: Somehow I did not get notifications for the discussion that happened in #156 between yesterday evening and this morning. I still think this PR might be relevant though, since we already had a special case to only merge word chars and char codes in a class range [in some cases](https://github.com/DmitrySoshnikov/regexp-tree/pull/157/files#diff-48e74382c584f8474d8aadcdb8af4beeR162).
=> Optimizer: CharClassClassrangesMerge: Only merge \w chars and char codes into class ranges

index.d.ts
- export interfaces
- rename Regexp interface to AstRegexp to avoid confusion with Regexp
- export generate and toRegExp functions
- add the '?' kind to the SimpleQuantifier interface
- make the 'to' parameter optional in RangeQuantifier
=> Change typescript definition file

index.d.ts
Adds type information and exports for `transform`, `traverse`, and some other exported functions.
=> Improve types for regexp-tree

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/index.js, src/regexp-tree.js
Makes it easier to disable some optimizations, as requested in eg. #199. Also adds some specific tests for one of the feature that's highlighted in #199 and is a partial fix for that issue.
=> Enable blacklisting of optimizations

package-lock.json, src/optimizer/README.md
Builds on #204 .
- Docs: Note difference between `regexp-tree` main `optimize` method and the optimizer method (esp. since `regexp-tree` README defers to this README)
=> Optimize API differences

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/transforms/__tests__/char-class-to-meta-transform-test.js, src/optimizer/transforms/char-class-to-meta-transform.js
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes#Types), `[\s]` should equivalent to `[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`
=> Fix `\s` rewrite

src/parser/__tests__/parser-basic-test.js, src/parser/generated/regexp-tree.js, src/parser/regexp.bnf
Sorry for #231. I'm still getting a hang of publishing packages and open source in general.
This PR modifies the parsing grammar to allow escaped hyphens inside character classes. All tests pass and I've even added a new one.
For the time being, I can `npm install https://github.com/just1ngray/regexp-tree` and it's working for my purposes. Just thought I'd create a PR in case it'd help anyone else.
=> Allow escaped hyphens in character classes

src/optimizer/__tests__/optimizer-integration-test.js, src/optimizer/transforms/__tests__/group-single-chars-to-char-class-test.js, src/optimizer/transforms/group-single-chars-to-char-class.js
Fixes https://github.com/DmitrySoshnikov/regexp-tree/issues/227
and fixes https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1231
=> Fix #227: treat "any single character" token as special in groupSingleCharsToCharClass

index.d.ts
I noticed the UnicodeProperty expression was not present in index.d.ts so here it is included.
Closes #226
=> Support UnicodeProperty in type definitions

src/compat-transpiler/runtime/index.js, src/parser/__tests__/parser-basic-test.js, src/parser/generated/regexp-tree.js, src/parser/regexp.bnf
The `hasIndices` or `/d` regex flag is part of ES2022.
> The `d` flag indicates that the result of a regular expression match should contain the start and end indices of the substrings of each capture group. It does not change the regex's interpretation or matching behavior in any way, but only provides additional information in the matching result.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices
=> fix: add support for `hasIndices` `/d` regex flag
