README.md
__tests__/integration-test.js
index.js
src/generator/index.js
src/parser/README.md
src/parser/__tests__/parser-basic-test.js
src/parser/__tests__/parser-test262-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Make `flags` an alpha-sorted string

---

src/generator/__tests__/generator-basic-test.js
src/generator/index.js

Fix empty groups, assertions, disjunctions

---

README.md
__tests__/integration-test.js
bin/regexp-tree
package.json
scripts/test
src/generator/__tests__/generator-basic-test.js
src/generator/index.js
src/parser/__tests__/parser-basic-test.js
src/parser/__tests__/parser-locations-test.js
src/parser/__tests__/parser-test262-test.js
src/traverse/__tests__/traverse-basic-test.js

Probably not the most useful PR, but still, worth a shot IMO.

Minor tweaks

---

src/parser/__tests__/parser-basic-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Support dotAll (\s) flag

---

src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Hoist `validFlags` const

---

src/parser/__tests__/parser-basic-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Add `symbol` on `Char` objects

---

src/parser/__tests__/parser-test262-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Throw on invalid unicode escapes

---

package.json

Explicitly state that this projects supports Node.js v6+ only.
https://github.com/DmitrySoshnikov/regexp-tree/pull/39#issuecomment-292106505

package.json: Add `engines`

---

src/traverse/__tests__/node-path-test.js
src/traverse/node-path.js

also: getForNode updates cached path if parameters are given

add setChild/appendChild

---

src/traverse/__tests__/node-path-test.js
src/traverse/node-path.js

* fixes #60
* fixes index != null for single child

fix for parent and parentPath not in sync and index != null for single child

---

README.md

type: assing -> assign

---

src/parser/__tests__/parser-test262-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

quantifier range boundaries check

---

.editorconfig
src/optimizer/README.md
src/optimizer/transforms/__tests__/group-single-chars-to-char-class-test.js
src/optimizer/transforms/group-single-chars-to-char-class.js
src/optimizer/transforms/index.js

(a|b|c) -> ([abc])
(?:a|b|c) -> [abc]

convert single chars group disjunction to chargroup

---

src/parser/__tests__/parser-test262-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

check for correct boundaries in char class range

---

src/optimizer/__tests__/optimizer-integration-test.js
src/optimizer/transforms/char-escape-unescape-transform.js

Correctly escape front and backslash

---

src/optimizer/__tests__/optimizer-integration-test.js
src/optimizer/transforms/char-escape-unescape-transform.js

Added some missing characters that were being optimized incorrectly (escape removed).

Preserve escape for dot and closing brace

---

bin/regexp-tree

Fixes DmitrySoshnikov/regexp-tree#84

Strip quotes from CLI input on Windows

---

src/optimizer/transforms/char-class-classranges-merge-transform.js

This just fixes a tiny typo in an comment.

Optimizer: Fix comment in char-class-classranges-merge transform

---

src/optimizer/transforms/__tests__/char-class-classranges-to-chars-transform-test.js
src/optimizer/transforms/char-class-classranges-to-chars-transform.js
src/optimizer/transforms/index.js

The transform is this PR handles the following optimizations:
`/[a-a$]/` -> `/[a$]/`
`/[a-b]/` -> `/[ab]/`

Optimizer: Simplifies class ranges spanning only one or two chars

---

bin/regexp-tree
package-lock.json
package.json

This PR replaces `nomnom` with `yargs` as proposed in #111.
CC @Golmote

CLI: replace nomnom with yargs

---

src/parser/__tests__/parser-basic-test.js
src/parser/generated/regexp-tree.js
src/parser/regexp.bnf

Parser: When u flag is set, throw error on invalid unicode escape

---

src/optimizer/transforms/__tests__/char-case-insensitive-lowercase-transform-test.js
src/optimizer/transforms/char-case-insensitive-lowercase-transform.js
src/optimizer/transforms/index.js

Optimizer: Transform Char to lowercase when i flag is set

---

src/optimizer/__tests__/optimizer-integration-test.js
src/optimizer/transforms/__tests__/char-escape-unescape-transform-test.js
src/optimizer/transforms/char-escape-unescape-transform.js

Optimizer: Unescape ] and fix unescape in class ranges

---

src/optimizer/transforms/__tests__/char-escape-unescape-transform-test.js
src/optimizer/transforms/char-escape-unescape-transform.js

Optimizer: Don't unescape space and # when x flag is set

---

README.md
__tests__/integration-test.js
src/regexp-tree.js
src/traverse/README.md
src/traverse/index.js

This is a working first pass at #147. Let me know your thoughts on the right API.

expose pre- and post- AST traverse hooks

---

src/optimizer/transforms/__tests__/ungroup-transform-test.js
src/optimizer/transforms/ungroup-transform.js

Optimizer: Ungroup: Merge Group content of type Alternative with parent Alternative

---

README.md
src/optimizer/README.md

Add documentation for the Optimizer module.
cf. #156 #157.

Optimizer: docs

---

package-lock.json
package.json

Info: https://app.snyk.io/test/npm/regexp-tree/0.1.0
yargs from v10 to v12 has some breaking changes, but they don't affect regex-tree. 
https://github.com/yargs/yargs/blob/master/CHANGELOG.md

Update yargs to resolve vulnerability of mem

---

package-lock.json

If you don't mind this rebase of `master`, fixes #203 . (I personally think it'd be good to reflect precisely what is on npm, so better than a merge, imo, despite it breaking anyone who has recently pointed to `master`, but I can change it to a merge--assuming you opt to "rebase" rather than "merge" this PR.)

Fixed master

---

index.d.ts

A few more type fixes.
Thanks again for the great lib!

Type fixes

---

src/optimizer/transforms/__tests__/char-class-classranges-merge-transform-test.js
src/optimizer/transforms/char-class-classranges-merge-transform.js

Return sort value for UnicodeProperty
